config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  resources :lists do
    resources :bookmarks, only: %i[new create destroy]
  end

  resources :moviebookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  has_many :moviebookmarks, dependent: :destroy
  has_many :movies, through: :moviebookmarks
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, uniqueness: true
  has_many :moviebookmarks
  has_many :bookmarks, through: :moviebookmarks
end

app/models/moviebookmark.rb
class Moviebookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :bookmark
  validates :movie_id, uniqueness: { scope: :bookmark_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

   # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  def new
    return unless @list.user == current_user

    @bookmark = Bookmark.new
  end

  def create
    return unless @list.user == current_user

    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, movie_ids: [])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]
  def index
    @lists = List.all
  end

  def show
    # set_list
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      respond_to do |format|
        format.html do
          redirect_to list_path(@list), notice: 'List created'
        end
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # set list
    return unless @list.user == current_user
  end

  def update
    return unless @list.user == current_user

    @list = List.update(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_others
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/moviebookmarks_controller.rb
class MoviebookmarksController < ApplicationController
  before_action :set_moviebookmark

  def destroy
    return unless @moviebookmark.bookmark.list.user == current_user

    @list = @moviebookmark.bookmark.list
    @moviebookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def set_moviebookmark
    @moviebookmark = Moviebookmark.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    # empty method
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/moviebookmarks_helper.rb
module MoviebookmarksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/_form.html.erb
<div class="form-new">
  <%= simple_form_for([list, bookmark]) do |f| %>
    <%= f.input :comment %>
    <%= f.association :movies, input_html: { data: { controller: "tom-select" } }%>
    <%= f.submit 'Add Movie', class: 'main-button'%>
  <% end %>
</div>

app/views/bookmarks/new.html.erb
  <div class="container w-100 mb-3">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-12 col-lg-6">
        <div class="container-list">
          <div class="form-modal">
            <%= render "shared/modal" do %>
              <div class="modal-container">
                <%= render "form", list: @list, bookmark: @bookmark %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WatchShack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= turbo_frame_tag "modal" %>
  </body>
</html>

app/views/lists/_listcard.html.erb
<% if list.movies.empty? %>
  <div class="flip-card">
    <div class="flip-card-inner">
      <div class="flip-card-front" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('assets/tema-cinema.jpg')">
        <h2 id="card-title"><%=list.name%></h2>
      </div>
      <div class="flip-card-back">
        <p>
          Add Movies
        </p>
      </div>
    </div>
  </div>
<% else %>
  <div class="flip-card">
    <div class="flip-card-inner">
      <div class="flip-card-front" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= list.movies.last.poster_url %>')">
       <h2 id="card-title"><%=list.name%></h2>
      </div>
      <div class="flip-card-back">
        <p>
          <ul>
            <% list.movies.each do |movie|%>
              <li><%=movie.title%></li>
            <% end %>
          </ul>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/lists/_moviecard.html.erb
<div class="movie_card" id="bright">
  <div class="info_section">
    <div class="movie_header">
      <!---<img class="locandina" src=<%= movie.poster_url %>/>--->
      <h1><%=movie.title%></h1>
      <p>by
        <% if movie.directors.size == 1 %>
          <%= movie.directors.first %>
        <% else %>
          <%= movie.directors.join(", ") %>
        <% end %>
      </p>
      <p>with
       <% if movie.actors.size == 1 %>
          <%= movie.actors.first %>
        <% else %>
          <%= movie.actors.first(5).join(", ") %>
        <% end %>
      </p>
      <span class="rating"><%=movie.rating%><i class="fa-solid fa-star"></i><span id="logo"><i class="fa-brands fa-imdb"></i></span></span>
    </div>
    <div class="movie_desc">
      <div class="text">
       <p><%=movie.overview%></p>
      </div>
    </div>
    <div class="director">
    </div>
  </div>
  <div class="blur_back bright_back" style="background-image: url('<%= movie.poster_url%>');"></div>
</div>

app/views/lists/_movielist.html.erb
<div class="movie-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= movie.poster_url %>')">
  <h4 id="title-film-card"><%=movie.title%></h4>
</div>

app/views/lists/_mycarousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
  <div class="row">
    <% list.movies.each_slice(3).each_with_index do |slice, index| %>
      <div class="carousel-inner">
        <div class="carousel-item <%= index.zero? ? 'active' : '' %> m-50">
          <div class="carousel-wrapper">
            <% slice.each do |movie| %>
              <div class="col-12 col-lg-4 ml-6" id="movie-flex">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-<%= movie.id %>">
                  <%= render "movielist", movie: movie %>
                </button>
              </div>
              <div class="modal fade" id="modal-<%= movie.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content" id="movie-modal">
                    <div class="modal-body">
                      <%= render 'moviecard', movie: movie%>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="title-div">
        <h1 id="big-title" class="text-center"><span class="font-color-secondary">WS</span> Lists<span class="red-char">.</span></h1>
        <%= link_to new_list_path, class: 'big-heart-button', data: { "turbo-frame": "modal" } do %>
          <i class="fa-solid fa-heart-circle-plus"
          data-controller="tooltip"
          data-bs-toggle="tooltip"
          data-bs-placement="right"
          title="Add your WS list"></i>
        <% end %>
      </div>
      <div class="cards-container">
        <div class="cards-grid">
          <% @lists.each do |list| %>
            <%= link_to list_path(list) do %>
              <%= render 'listcard', list: list %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
  <div class="container w-100 mb-3">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-12 col-lg-6">
        <div class="container-list">
          <div class="form-modal">
            <%= render "shared/modal" do %>
              <div class="modal-container">
                <h1 class="big-title">Create a New List</h1>
                  <%= simple_form_for @list do |f| %>
                    <%= f.input :name %>
                    <%= f.submit class: "main-button" %>
                  <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/lists/show.html.erb
<div class="container mb-3">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="title-div">
        <h1 id="big-title" class="text-center"><%= @list.name %></h1>
        <%= link_to new_list_bookmark_path(@list), class: 'big-heart-button', data: { "turbo-frame": "modal" } do %>
          <i class="fa-solid fa-heart-circle-plus"
          data-controller="tooltip"
          data-bs-toggle="tooltip"
          data-bs-placement="right"
          title="Add Movie"></i>
        <% end %>
      </div>
      <div class="movie-carousel">
        <%= render 'mycarousel', list: @list %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container mb-3">
  <div class="row">
    <div class="col-sm-12 col-md-6 col-lg-6">
    </div>
    <div class="col-sm-12 col-md-6 col-lg-6 order-md-last">
      <div class="container-welcome">
        <div class="big-title-div mb-3">
          <h1 id="big-title"><span class="red-char">W</span>atch<span class="red-char">S</span>hack<span class="red-char">.</span></h1>
          <p class="messages-homepage text-center"><span data-controller="typed-js"></span></p>
        </div>
        <div class="user-actions">
        <% if current_user.nil? %>
          <%= render template: "devise/sessions/new" %>
          <%= link_to "New here? Sign up!", new_user_registration_path, class: "messages-homepage" %>
          <p class="m-3">Or</p>
          <%= link_to "Forgot your password?", new_user_password_path, class: "messages-homepage" %>
        <% else %>
          <%= link_to raw('Explore  <i class="fa-solid fa-film"></i>'), lists_path, class: "main-button", id:"home-button"%>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <div data-controller="modal" data-action="keyup@document->modal#handleKeyup"> <!-- Clicking outside the modal will close will cause it to close -->
    <div data-action="click->modal#close"></div>
    <div>
        <%= turbo_frame_tag "modal-body" do %>
          <%= yield %>
        <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-watchlist">
  <div class="container-fluid">
    <%= link_to root_path, class:"navbar-mybrand" do %>
      <h3>WS<span class="span-color">Home</span></h3>
    <%end%>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to lists_path do %>
            <h3>All<span class="span-color">WSLists</span></h3>
          <%end%>
        </li>
        <li class="nav-item dropdown">
            <% if current_user.nil? %>
              <%= link_to "Login", new_user_session_path %>
            <% else %>
              <%= current_user.username %>
            <% end %>

            <%= image_tag "avatar_default.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>